---
title: "American Slavery"
author: "Zach Eisenstein"
subtitle: "Tidy Tuesday 2020-06-16"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(scales)
library(tidytuesdayR)
theme_set(theme_light())

tuesdata <- tidytuesdayR::tt_load('2020-06-16')

census <- tuesdata$census
slave_routes <- tuesdata$slave_routes
african_names <- tuesdata$african_names
blackpast <- tuesdata$blackpast

```

## Explore Census

```{r}

tuesdata

census %>%
  distinct(region)

census %>%
  distinct(region, division)
# maps 1 to 1

census %>%
  filter(region == "USA Total") %>%
  summarise(sum(total))

census %>%
  filter(!is.na(division)) %>%
  summarise(sum(total))

# divisions sum equals total
# will use divisions exclusively
census <- census %>%
  filter(!is.na(division))

# add other
census <- census %>%
  mutate(other = total - white - black)

census_long <- census %>%
  select(-total, -black) %>%
  pivot_longer(
    cols = c(white, black_free, black_slaves, other),
    names_to = "group",
    values_to = "pop"
  ) %>%
  mutate(group = fct_reorder(group, pop, sum))


```

## Demographics by region

```{r}
census_long %>%
  ggplot() +
  geom_col(aes(x = year, y = pop, fill = group)) +
  facet_wrap(~ region)
```

What was the growth in black slaves leading up to the emancipation?

```{r}
gg_dat <- census_long %>%
  filter(group == "black_slaves") %>%
  count(year, wt = pop, name = "pop") %>%
  arrange(year) %>%
  mutate(pct_growth = (pop/lag(pop) - 1))

ggplot(gg_dat) + 
  geom_col(aes(x = year, y = pct_growth)) + 
  geom_text(aes(x = year, y = pct_growth, label = percent(pct_growth, accuracy = .1)),
            nudge_y = ifelse(gg_dat$pct_growth > 0, 0.05, -0.05)
            ) +
  ggtitle("Percentage Growth Black Slave Population")
```


## Slave Routes

```{r}
head(slave_routes)

ggplot(slave_routes, aes(year_arrival)) +
  geom_histogram()

slave_routes %>%
  filter(fct_lump(port_arrival, 10) != "Other") %>%
  count(port_arrival, wt = n_slaves_arrived, sort = TRUE) %>%
  mutate(port_arrival = fct_reorder(port_arrival, n, sum)) %>%
  ggplot(aes(n, port_arrival)) +
  geom_col() +
  scale_x_continuous(label = comma) +
  labs(title = "Ports accepting greatest number of slaves",
       subtitle = "Years (1514 - 1866)",
       x = "Number of Slaves",
       y = "Port of Arrival")
```

